local wk = require("which-key")

wk.add({
    { "<leader>cp", "<cmd>let @+ = expand('%:p') <CR>", desc = "Copy file path" },
    { "<leader>p", "<cmd>CocCommand prettier.forceFormatDocument <CR>", desc = "Toggle Prettier" },
    { "<leader>r", "<cmd>!node %:p <CR>", desc = "Run js file" },
    { "<leader>l", "<cmd>CocCommand eslint.executeAutofix <CR>", desc = "ESlint fix" },
    { "<leader>f", group = "telescope" },
    { "<leader>fb", "<cmd>Telescope file_browser path=/home/andrei/<CR>", desc = "Browse ~/" },
    { "<leader>fg", "<cmd>lua require('telescope.builtin').git_branches()<CR>", desc = "Find git branches" },
    { "<leader>fc", "<cmd>Telescope file_browser path=%:p:h<CR>", desc = "Browse current directory" },
    { "<leader>ff", "<cmd>lua require('telescope.builtin').find_files({ cwd = vim.fn.expand('%:p:h') })<CR>", desc = "Find file" },
    { "<leader>fh", "<cmd>Telescope oldfiles<CR>", desc = "Find in history" },
    { "<leader>fo", "<cmd>Telescope buffers<CR>", desc = "Find opened files" },
    { "<leader>fw", "<cmd>Telescope live_grep search_dirs={vim.fn.expand('%:p:h')}<CR>", desc = "Find word" },
    { "<leader>g", group = "git" },
    { "<leader>gn", "<cmd>Neogit<CR>", desc = "Open neogit" },
    { "<leader>gp", "<cmd>Gitsigns preview_hunk_inline<CR>", desc = "Preview hunk" },
    { "<leader>gr", "<cmd>Gitsigns reset_hunk<CR>", desc = "Reset hunk" },
    { "<leader>j", "<Plug>(easymotion-bd-f)", desc = "Jump to char" },
    { "<leader>n", "<cmd>NERDTreeToggle %<CR>", desc = "Open NERDTree" },
    { "<leader>q", "<cmd>qa<CR>", desc = "Save & Quit" },
    { "<leader>s", "<C-^>", desc = "Switch between buffers" },
    { "<leader>t", "<cmd>call OpenTerminal()<CR>", desc = "Open terminal" },
    { "<leader>w", group = "windows" },
    { "<leader>wc", "<C-w>q", desc = "Close window" },
    { "<leader>wd", "<cmd>vertical resize -10<CR>", desc = "Decrease size" },
    { "<leader>wh", "<C-w>h", desc = "Go left" },
    { "<leader>wi", "<cmd>vertical resize +10<CR>", desc = "Increase size" },
    { "<leader>wj", "<C-w>j", desc = "Go right" },
    { "<leader>wk", "<C-w>k", desc = "Go up" },
    { "<leader>wl", "<C-w>l", desc = "Go down" },
    { "<leader>ws", "<C-w><C-r>", desc = "Swap windows" },
    { "<leader>wv", "<C-w>v", desc = "Vertical split" },
})
